### ISSUE TITLE
Publish lawnchair to NPM

### ISSUE THREAD

**Issue by adamshih** [brianleroux/lawnchair#193]
It'd be useful to be able to get lawnchair from NPM.

**Comment by auser** [comment]
+1

**Comment by DjebbZ** [comment]
Still not published today... Any progress so far ?

**Comment by MarkMYoung** [comment]
I don't know why it took me 50 minutes, but it is available now.
[npmjs.com/package/lawnchair] (https://www.npmjs.com/package/lawnchair)
`npm install lawnchair`
Enjoy!

**Comment by DjebbZ** [comment]
Wonderful ! Thanks a lot.

**Comment by qq40660** [comment]
goodjob
