### ISSUE TITLE
Adapter include vs adapter choice order

### ISSUE THREAD

**Issue by demaniak** [brianleroux/lawnchair#213]
Hi.
In firefox 36.0.4, I included Lawnchair and adapters like so:

    <script src="scripts/vendor/lawnchair/Lawnchair.js"></script>
    <script src="scripts/vendor/lawnchair/memory.js"></script>  
    <script src="scripts/vendor/lawnchair/indexed-db.js"></script> 

In this order, indexed-db adapter get's picked.

If you reverse memory and indexed-db link order, then memory get's picked. Both adapters are valid when not running in private window (private window is why I was tinkering with memory adapter).

The reason seems to be the use of `Lawnchair.adapters.splice(0,0,obj);` in `Lawnchair.adapter` (last line). The comment there also implies that the LAST valid adapter found will become the preferred adapter. 
This is technically fine, but the Lawnchair docs indicate that the FIRST valid adapter will be used.
Causes some confusion, especially if you are greedy and trying to have it all.

Suggestion: either update the docs to reflect the current state of affairs, or change `Lawnchair.adapter` to `push` a new valid adapter onto the `adapters` array.

**Comment by ppbntl19** [comment]
I am also having same issue.Please help me if you have any solution  for this.

**Comment by MarkMYoung** [comment]
I think @brianleroux used 'splice' to mutate the array in-place without using 'unshift' followed by an assignment.  Please test pull request #223 to your satisfaction.
