### ISSUE TITLE
a query returns 1 instead of 2

### ISSUE THREAD

**Issue by a42** [brianleroux/lawnchair#214]
Hi there 

Following .where returns 1 instead of 2:

var ppl = Lawnchair('people', function(r) {

});

    ppl.save({person:'rip', key:'2'}, 'console.log(record)')
    ppl.save({person:'rip', key:'2'}, 'console.log(record)')
    ppl.save({person:'rap', key:'3'}, 'console.log(record)')
    ppl.save({person:'rup', key:'4'}, 'console.log(record)')
    ppl.save({person:'rup', key:'4'}, 'console.log(record)')
       
    ppl.where('record.person === "rup"', 'console.log(records.length)')

As you see I save person:rup twice so should the ppl.where not return 2 in the console.log ?

Cheers,
Adam

**Comment by taybin** [comment]
This should return 1 because the key is '4', so it updates the existing record.
