### ISSUE TITLE
JSON.parse(window.top.name) can cause all JS to stop executing

### ISSUE THREAD

**Issue by mkoryak** [brianleroux/lawnchair#70]
We just had a major issue on the site due to this bug.
in the 'window-name' adapter, there is a call:

data = window.top.name ? JSON.parse(window.top.name) : {}

when the window.top.name is not valid json, this will throw an exception which causes all JS loaded after this to fail.

fix is:

var data;
    try {
        data = window.top.name ? JSON.parse(window.top.name) : {}
    } catch(e){
        data = {};
    }

**Comment by mkoryak** [comment]
So, i assume this is never going to be fixed, right?

**Comment by MarkMYoung** [comment]
This was [fixed over 3 years ago](https://github.com/brianleroux/lawnchair/commit/b89c3b661782ba510526632234cc5256087f1e9c#diff-4e36d0da6d18ac20fe1f79b1db2f8a94) without an update to this bug.

**Comment by qq40660** [comment]
mark
